manifestVersion: subsquid.io/v0.1
name: gs-stats-polkadot
version: 3
description: |-
  Giant Squid Stats squid for Polkadot chain
build:

deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: polkadot
    cmd: [ "node", "lib/main" ]
  api:
    cmd: [ "npx", "squid-graphql-server", "--dumb-cache", "in-memory", "--dumb-cache-ttl", "1000", "--dumb-cache-size", "100", "--dumb-cache-max-age", "1000" ]

scale:
  dedicated: true
  processor:
    profile: large
  addons:
    postgres:
      storage: 50Gi
